@echo off 
if exist .\"TicTacToe Networking" (
    rmdir /s /q "TicTacToe Networking"
    echo. && echo Deleted original folder of TicTacToe Networking!
)
pyinstaller --onedir TicTacToe-Networking.py --name "TicTacToe Networking" && echo. && echo Successfully created the executable file for TicTacToe Networking!
move dist\"TicTacToe Networking" . && echo. && echo Moved directory successfully!
rmdir dist && echo. && echo Successfully removed dist folder...
rmdir /s /q build && echo. && echo Successfully removed build folder...
rmdir /s /q __pycache__ && echo. && echo Successfully removed __pycache__ folder...
del *.spec && echo. && echo Successfully removed the spec file...